[WIP] Initial draft
PumasAI-Labs/Data-Wrangling pull request #1
Opened 2023-06-21 22:07 UTC by jotas6

# Status

- [x] Update README file
- [ ] Code examples
- [ ] Add content to home page
- [ ] Reference sheet
- [ ] Instructor notes
- [ ] Schedule

2023-06-29 15:10 UTC, jotas6 commented
I took inspiration from our tutorials and https://juliadatascience.io/, but I am not sure about what is the best way to give credits here. The same happens for the [Julia workshop](https://github.com/PumasAI-Labs/Julia-Workshop).

2023-07-11 17:06 UTC, storopoli requested changes
Some changes requests and also some suggestions.

2023-07-11 17:06 UTC, storopoli commented on 04-grouping.jl
> +groupby(df, :ISMALE) # Group subjects according to sex
This returns a `GroupedDataFrame` (or something similar if I am not mistaken). Should we care to explain this?

2023-07-11 17:06 UTC, storopoli commented on 04-grouping.jl
> +## More complicated example: transform + group
```suggestion
## More complicated example: @transform + groupby
```

2023-07-11 17:06 UTC, storopoli commented on 04-grouping.jl
> +## Tip: groupby can take multiple columns
```suggestion
## Tip: groupby can take multiple columns as grouping keys
```

2023-07-11 17:06 UTC, storopoli commented on 04-grouping.jl
> +# Combining (@combine)
Maybe Summarizing instead of Combining?
What you thin?

2023-07-11 18:00 UTC, jotas6 commented on 03-transform.jl
> +@transform df :ISMALE = [i == 0 ? "Female" : "Male" for i in :ISMALE] # Modify an existing column
I am not sure if this is enough or what we are looking for, but this part might be related: https://github.com/PumasAI-Labs/Julia-Workshop/blob/cca736d6de5ff0d815834c9ec8defb61b7d16b76/01-variables/04-containers.jl#L3C1-L6C29

2023-07-11 18:17 UTC, storopoli commented on 03-transform.jl
> +@transform df :ISMALE = [i == 0 ? "Female" : "Male" for i in :ISMALE] # Modify an existing column
Yeah, then we need to either change this part or explain the `[f(i) for i in collection]` syntax.

2023-07-11 18:31 UTC, jotas6 commented on 03-transform.jl
> +@transform df :ISMALE = [i == 0 ? "Female" : "Male" for i in :ISMALE] # Modify an existing column
I included a short explanation of array comprehensions in the loops section, but I don't know if it is detailed enough: https://github.com/PumasAI-Labs/Julia-Workshop/blob/cca736d6de5ff0d815834c9ec8defb61b7d16b76/02-syntax/02-loops.jl#L50C1-L57C46

I could add more examples there or modify this example if that would be better.

2023-07-11 18:42 UTC, jotas6 commented on 04-grouping.jl
> +# Combining (@combine)
I think that is a better name. I went with the same name as the macro, but summarizing is probably more descriptive

2023-07-11 18:48 UTC, jotas6 commented on 04-grouping.jl
> +groupby(df, :ISMALE) # Group subjects according to sex
Yes, it returns a `GroupedDataFrame` and it looks like it is possible to manipulate the results (https://dataframes.juliadata.org/stable/lib/functions/#DataFrames.groupby), but I was afraid that might be too much information. 

I also think that the main use case for `groupby` is to split data and then use `combine` or `@combine`, but I could definitely work on some examples that involve using `GroupedDataFrame`s.

2023-07-11 18:49 UTC, jotas6 commented
Sorry about forgetting to add `.jl` at the end of the package names

2023-07-12 13:10 UTC, storopoli commented on 04-grouping.jl
> +groupby(df, :ISMALE) # Group subjects according to sex
Yes, then don't mention it. Maybe in the instructor's notes?

2023-07-12 13:10 UTC, storopoli commented
> Sorry about forgetting to add `.jl` at the end of the package names

Yeah specially around `DataFrames.jl` ecosystem is very confusing.

2023-07-12 13:26 UTC, jotas6 commented on 04-grouping.jl
> +groupby(df, :ISMALE) # Group subjects according to sex
Yes, I agree. I will add a note about it in the instructor notes

2023-07-18 17:05 UTC, merged